matrix:
  include:
    - os: osx
      env: HOMEBREW_BUILD_FROM_SOURCE=1
      osx_image: beta-xcode6.1

before_install:
  - env
  - brew update
  - brew upgrade cmake
  - brew install openssl
  - brew tap dennisdegreef/qt5

script:
  - source print-to-break-silence.sh
  - bust_log_silence_limit &
  - brew install --verbose --debug --build-bottle --universal --without-webengine dennisdegreef/qt5/qt5
  - brew bottle dennisdegreef/qt5/qt5
  - brew install --verbose --debug --build-bottle --universal dennisdegreef/qt5/qtkeychain
  - brew bottle dennisdegreef/qt5/qtkeychain

