matrix:
  include:
    - os: osx
      osx_image: beta-xcode6.1

before_install:
  - env
  - brew update
  - brew upgrade cmake
  - brew install openssl
  - brew tap dennisdegreef/qt5

script:
  - source print-to-break-silence.sh
  - bust_log_silence_limit &
  - brew install dennisdegreef/qt5/qt5
